"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_url": "https://cloudnetservice.crowdin.com"

"preserve_hierarchy": true

"files": [
    # JSON translation files
    {
      "source": "/i18n/en/**/*",
      "translation": "/i18n/%two_letters_code%/**/%original_file_name%",
    },
    # Blog Markdown files
    {
      "source": "/blog/**/*",
      "translation": "/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%",
    },
    # (Versioned) Docs Markdown files
    {
      "source": "/versioned_docs/**/*",
      "translation": "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%",
      "ignore":
        [
          "/**/*.js",
          "/**/*.jsx",
          "/**/*.ts",
          "/**/*.tsx",
          "/**/*.css",
          "/**/*.png",
          "/**/*.svg",
        ],
    },
  ]
