name: Website Yarn Build

on: [ create, push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install yarn
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: website-node${{ matrix.node }}-${{ github.sha }}
          path: build/