name: Website Yarn Build

on: [ create, push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CloudNet Website Build

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Install yarn
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Sync translations
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        if: ${{ github.ref == 'refs/heads/development' }}
        run: yarn run crowdin:sync
      - name: Download translations
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn run crowdin download
      - name: Build website
        run: yarn build
      - name: Copy robots.txt to non-productive envs
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: canastro/copy-file-action@master
        with:
          source: "template/robots.txt"
          target: "build/robots.txt"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: cloudnetservice-website-node14-${{ github.sha }}
          path: build/
